# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw1UI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 458)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 251, 401))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.btn1_1 = QtWidgets.QPushButton(self.groupBox)
        self.btn1_1.setGeometry(QtCore.QRect(10, 50, 229, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn1_1.setFont(font)
        self.btn1_1.setAutoRepeatDelay(-2)
        self.btn1_1.setFlat(False)
        self.btn1_1.setObjectName("btn1_1")
        self.btn1_2 = QtWidgets.QPushButton(self.groupBox)
        self.btn1_2.setGeometry(QtCore.QRect(10, 110, 229, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn1_2.setFont(font)
        self.btn1_2.setObjectName("btn1_2")
        self.btn1_4 = QtWidgets.QPushButton(self.groupBox)
        self.btn1_4.setGeometry(QtCore.QRect(10, 290, 229, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn1_4.setFont(font)
        self.btn1_4.setObjectName("btn1_4")
        self.btn1_5 = QtWidgets.QPushButton(self.groupBox)
        self.btn1_5.setGeometry(QtCore.QRect(10, 350, 229, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn1_5.setFont(font)
        self.btn1_5.setDefault(False)
        self.btn1_5.setObjectName("btn1_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 229, 131))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn1_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn1_3.setGeometry(QtCore.QRect(0, 92, 229, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn1_3.setFont(font)
        self.btn1_3.setObjectName("btn1_3")
        self.Input1_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.Input1_1.setGeometry(QtCore.QRect(120, 40, 100, 30))
        self.Input1_1.setText("")
        self.Input1_1.setObjectName("Input1_1")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 10, 251, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn2_1 = QtWidgets.QPushButton(self.groupBox_3)
        self.btn2_1.setGeometry(QtCore.QRect(10, 110, 229, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn2_1.setFont(font)
        self.btn2_1.setAutoRepeatDelay(-2)
        self.btn2_1.setFlat(False)
        self.btn2_1.setObjectName("btn2_1")
        self.btn2_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.btn2_2.setGeometry(QtCore.QRect(10, 180, 229, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn2_2.setFont(font)
        self.btn2_2.setAutoRepeatDelay(-2)
        self.btn2_2.setFlat(False)
        self.btn2_2.setObjectName("btn2_2")
        self.Input2_1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.Input2_1.setGeometry(QtCore.QRect(10, 40, 231, 30))
        self.Input2_1.setText("")
        self.Input2_1.setObjectName("Input2_1")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(270, 230, 251, 181))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.btn3_1 = QtWidgets.QPushButton(self.groupBox_4)
        self.btn3_1.setGeometry(QtCore.QRect(10, 70, 229, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn3_1.setFont(font)
        self.btn3_1.setAutoRepeatDelay(-2)
        self.btn3_1.setFlat(False)
        self.btn3_1.setObjectName("btn3_1")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(530, 10, 251, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.btn4_1 = QtWidgets.QPushButton(self.groupBox_5)
        self.btn4_1.setGeometry(QtCore.QRect(10, 40, 229, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn4_1.setFont(font)
        self.btn4_1.setAutoRepeatDelay(-2)
        self.btn4_1.setFlat(False)
        self.btn4_1.setObjectName("btn4_1")
        self.btn4_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.btn4_2.setGeometry(QtCore.QRect(10, 110, 229, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn4_2.setFont(font)
        self.btn4_2.setAutoRepeatDelay(-2)
        self.btn4_2.setFlat(False)
        self.btn4_2.setObjectName("btn4_2")
        self.btn4_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.btn4_3.setGeometry(QtCore.QRect(10, 180, 229, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn4_3.setFont(font)
        self.btn4_3.setAutoRepeatDelay(-2)
        self.btn4_3.setFlat(False)
        self.btn4_3.setObjectName("btn4_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "1. Calibration"))
        self.btn1_1.setText(_translate("MainWindow", "1.1 Corner Detection "))
        self.btn1_2.setText(_translate("MainWindow", "1.2 Find Intrinsic "))
        self.btn1_4.setText(_translate("MainWindow", "1.4 Find Distortion"))
        self.btn1_5.setText(_translate("MainWindow", "1.5 Show Result"))
        self.groupBox_2.setTitle(_translate("MainWindow", "1.3 Find Extrinsic"))
        self.btn1_3.setText(_translate("MainWindow", "1.3 Find Extrinsic"))
        self.label_2.setText(_translate("MainWindow", "Select image:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "2. Augmented Reality "))
        self.btn2_1.setText(_translate("MainWindow", "2.1 Show words on board"))
        self.btn2_2.setText(_translate("MainWindow", "2.2 Show words vertically"))
        self.groupBox_4.setTitle(_translate("MainWindow", "3. Stereo Disparity Map"))
        self.btn3_1.setText(_translate("MainWindow", "3.1 Stereo Disparity Map"))
        self.groupBox_5.setTitle(_translate("MainWindow", "4. SIFT"))
        self.btn4_1.setText(_translate("MainWindow", "4.1 Keypoints"))
        self.btn4_2.setText(_translate("MainWindow", "4.2 Matched Keypoints"))
        self.btn4_3.setText(_translate("MainWindow", "4.3 Warp Images"))

