# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw1_5.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(220, 295)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_2.setGeometry(QtCore.QRect(10, 50, 200, 30))
        self.button_2.setObjectName("button_2")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_1.setGeometry(QtCore.QRect(10, 10, 200, 30))
        self.button_1.setObjectName("button_1")
        self.button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_5.setGeometry(QtCore.QRect(10, 210, 200, 30))
        self.button_5.setObjectName("button_5")
        self.button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4.setGeometry(QtCore.QRect(10, 130, 200, 30))
        self.button_4.setObjectName("button_4")
        self.button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_3.setGeometry(QtCore.QRect(10, 90, 200, 30))
        self.button_3.setObjectName("button_3")
        self.spin_1 = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_1.setGeometry(QtCore.QRect(10, 170, 200, 30))
        self.spin_1.setMaximum(9999)
        self.spin_1.setObjectName("spin_1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 220, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "5.0 Training Cifar10 Classifier Using VGG16"))
        self.button_2.setText(_translate("MainWindow", "2. Show Hyperparameters"))
        self.button_1.setText(_translate("MainWindow", "1. Show Train Images"))
        self.button_5.setText(_translate("MainWindow", "5. Test"))
        self.button_4.setText(_translate("MainWindow", "4. Show Accuracy"))
        self.button_3.setText(_translate("MainWindow", "3. Show Model Structure"))
